name: Build and Execute UT Runner 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image and run tests
      run: docker run -v ${{ github.workspace }}/src/Main:/main -v ${{ github.workspace }}/src/Test:/test $(docker build -q .)
