name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image and run tests
      run: docker run -v ./src/Main:/main -v ./src/Test:/test $(docker build . --file Dockerfile)
